### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by v-alje**
Build.Reason:Manual by Alma Jenks
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=316672&view=results
 source_repo.branch:master
 source_repo.url:https://apidrop.visualstudio.com/_git/binaries

### CODE REVIEW

**Comment by v-alje** [comment]
Docs Build status updates of commit _[43f27e9](https://github.com/dotnet/msbuild-api-docs/commits/43f27e9e1d3d4476c4267f37ba81453e30af7093)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msbuild-api-docs/xml/Microsoft.Build.Utilities/ToolLocationHelper.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Utilities/ToolLocationHelper.xml) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.toollocationhelper?view=msbuild-17-netcore&branch=pr-en-us-13) | [Details](#user-content-a8553450a5d10b09906a17119fe4e04b-0b6a81ba)
[msbuild-api-docs/xml/FrameworksIndex/msbuild-17.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/FrameworksIndex/msbuild-17.xml) | :white_check_mark:Succeeded | |
[msbuild-api-docs/xml/FrameworksIndex/msbuild-17-netcore.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/FrameworksIndex/msbuild-17-netcore.xml) | :white_check_mark:Succeeded | |
[msbuild-api-docs/xml/Microsoft.Build.BuildEngine/Engine.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.BuildEngine/Engine.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.buildengine.engine?view=netframework-4.8&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Evaluation/ProjectCollection.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Evaluation/ProjectCollection.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.projectcollection?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Execution/BuildManager.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Execution/BuildManager.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.execution.buildmanager?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Execution/HostServices.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Execution/HostServices.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.execution.hostservices?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Framework.Profiler/EvaluationLocation.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Framework.Profiler/EvaluationLocation.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework.profiler.evaluationlocation?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Framework/BuildEventContext.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Framework/BuildEventContext.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework.buildeventcontext?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Tasks/DownloadFile.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Tasks/DownloadFile.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.downloadfile?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Tasks/ResolveSDKReference.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Tasks/ResolveSDKReference.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.resolvesdkreference?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Utilities/AppDomainIsolatedTask.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Utilities/AppDomainIsolatedTask.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.appdomainisolatedtask?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Utilities/AssemblyFoldersExInfo.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Utilities/AssemblyFoldersExInfo.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.assemblyfoldersexinfo?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Utilities/ProcessorArchitecture.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Utilities/ProcessorArchitecture.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.processorarchitecture?view=msbuild-17-netcore&branch=pr-en-us-13) |
[msbuild-api-docs/xml/Microsoft.Build.Utilities/ToolTask.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Utilities/ToolTask.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.tooltask?view=msbuild-17-netcore&branch=pr-en-us-13) |

<a id="a8553450a5d10b09906a17119fe4e04b-0b6a81ba"></a>
### [msbuild-api-docs/xml/Microsoft.Build.Utilities/ToolLocationHelper.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test-2/msbuild-api-docs/xml/Microsoft.Build.Utilities/ToolLocationHelper.xml)
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'param' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/247c10ab-603c-d60f-b1c9-802cdb98e28c/202209012139573008-13/BuildReport?accessString=323ce1056cafc65552a751a706c9d360ccf861f2d775a7c8fd7b5a8887fca4b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/247c10ab-603c-d60f-b1c9-802cdb98e28c?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ghogen** [comment]
@v-alje This looks fine. I'll look into the warning for a possible fix in MSBuild sources for 17.4, but it doesn't affect the build as far as I can tell.

**Review by ghogen — APPROVED** [review]

**Comment by v-alje** [comment]
@ghogen Thank you!

**Comment by ghogen** [comment]
Thanks, @v-alje !

**Comment by ghogen** [comment]
Entered MSBuild issue and PR to fix warning
https://github.com/dotnet/msbuild/issues/7938

**Pull request merged**
